# Generated by Django 2.0.1 on 2018-01-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensereport', '0003_expensereport_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseitem',
            name='telephone',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
